package main

import (
	"context"
	"flag"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/caiatech/govc/api"
	"github.com/caiatech/govc/config"
	"github.com/caiatech/govc/logging"
	"github.com/gin-gonic/gin"

	// Swagger imports
	_ "github.com/caiatech/govc/docs" // This will be generated by swag
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

var (
	configFile = flag.String("config", "", "Path to configuration file (optional)")
	debug      = flag.Bool("debug", false, "Enable debug mode (overrides config)")
	version    = flag.Bool("version", false, "Show version information")
)

const (
	AppVersion = "1.0.0-dev"
	BuildTime  = "unknown"
)

// @title GOVC API
// @version 1.0.0-dev
// @description A high-performance Git version control system API with memory-first architecture
// @termsOfService https://github.com/caiatech/govc/blob/main/LICENSE

// @contact.name GOVC API Support
// @contact.url https://github.com/caiatech/govc/issues
// @contact.email support@caiatech.com

// @license.name MIT
// @license.url https://github.com/caiatech/govc/blob/main/LICENSE

// @host localhost:8080
// @BasePath /api/v1

// @securityDefinitions.basic BasicAuth

// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name Authorization
// @description Enter the token with the `Bearer: ` prefix, e.g. "Bearer abcde12345"

// @securityDefinitions.apikey ApiKeyQuery
// @in query
// @name api_key
// @description API key for accessing the API

// @tag.name Repository Management
// @tag.description Operations for managing Git repositories

// @tag.name Git Operations
// @tag.description Core Git operations like add, commit, checkout

// @tag.name Authentication
// @tag.description Authentication and authorization endpoints

// @tag.name Health & Monitoring
// @tag.description Health checks and monitoring endpoints

// @tag.name V2 Architecture
// @tag.description Clean architecture V2 API endpoints

func main() {
	flag.Parse()

	// Show version and exit
	if *version {
		fmt.Printf("govc-server %s\n", AppVersion)
		fmt.Printf("Build time: %s\n", BuildTime)
		os.Exit(0)
	}

	// Load configuration
	cfg, err := config.LoadConfig(*configFile)
	if err != nil {
		// Use basic log here since logger not yet initialized
		log.Fatalf("Failed to load configuration: %v", err)
	}

	// Override debug mode from command line
	if *debug {
		cfg.Development.Debug = true
	}

	// Initialize logger early
	logConfig := logging.Config{
		Level:     logging.LogLevel(cfg.GetLogLevel()),
		Component: cfg.Logging.Component,
		Output:    os.Stdout,
	}
	logger := logging.NewLogger(logConfig)
	
	logger.WithFields(map[string]interface{}{
		"version":    AppVersion,
		"build_time": BuildTime,
		"debug":      cfg.Development.Debug,
	}).Info("Starting govc server")

	// Set Gin mode based on configuration
	if cfg.Development.Debug {
		gin.SetMode(gin.DebugMode)
	} else {
		gin.SetMode(gin.ReleaseMode)
	}

	// Create router with middleware
	router := gin.New()

	// Add recovery middleware (logging is handled by the logger directly)

	// Add recovery middleware
	router.Use(gin.Recovery())

	// Add CORS middleware if enabled
	if cfg.Development.CORSEnabled {
		router.Use(corsMiddleware(cfg.Development.AllowedOrigins))
	}

	logger.Info("Initializing server components")

	// Create server with config
	server := api.NewServer(cfg)

	// Register routes
	server.RegisterRoutes(router)

	// Add Swagger UI endpoint
	if cfg.Development.Debug {
		router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
		logger.WithField("endpoint", "/swagger/index.html").Info("Swagger UI enabled")
	}

	// Create HTTP server with proper timeouts
	addr := cfg.Address()
	srv := &http.Server{
		Addr:         addr,
		Handler:      router,
		ReadTimeout:  cfg.Server.ReadTimeout,
		WriteTimeout: cfg.Server.WriteTimeout,
		IdleTimeout:  cfg.Server.IdleTimeout,
	}

	// Start server in a goroutine
	go func() {
		logger.WithFields(map[string]interface{}{
			"address":         addr,
			"read_timeout":    cfg.Server.ReadTimeout,
			"write_timeout":   cfg.Server.WriteTimeout,
			"idle_timeout":    cfg.Server.IdleTimeout,
		}).Info("Starting HTTP server")
		
		if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			logger.WithField("error", err.Error()).Fatal("Failed to start server")
		}
	}()

	// Wait for interrupt signal to gracefully shutdown the server
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	sig := <-quit
	
	logger.WithField("signal", sig.String()).Info("Received shutdown signal")

	// Give outstanding requests 30 seconds to complete
	shutdownTimeout := 30 * time.Second
	ctx, cancel := context.WithTimeout(context.Background(), shutdownTimeout)
	defer cancel()

	logger.WithField("timeout", shutdownTimeout).Info("Gracefully shutting down server")

	// Shutdown server
	if err := srv.Shutdown(ctx); err != nil {
		logger.WithField("error", err.Error()).Error("Server forced to shutdown")
		os.Exit(1)
	}

	// Close server resources
	server.Close()
	logger.Info("Server shutdown completed")
}

func corsMiddleware(allowedOrigins []string) gin.HandlerFunc {
	return func(c *gin.Context) {
		origin := c.Request.Header.Get("Origin")

		// Check if origin is allowed
		allowed := false
		for _, allowedOrigin := range allowedOrigins {
			if allowedOrigin == "*" || allowedOrigin == origin {
				allowed = true
				break
			}
		}

		if allowed {
			c.Writer.Header().Set("Access-Control-Allow-Origin", origin)
		} else if len(allowedOrigins) > 0 && allowedOrigins[0] == "*" {
			c.Writer.Header().Set("Access-Control-Allow-Origin", "*")
		}

		c.Writer.Header().Set("Access-Control-Allow-Credentials", "true")
		c.Writer.Header().Set("Access-Control-Allow-Headers", "Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization, accept, origin, Cache-Control, X-Requested-With, X-API-Key")
		c.Writer.Header().Set("Access-Control-Allow-Methods", "POST, OPTIONS, GET, PUT, DELETE, PATCH")

		if c.Request.Method == "OPTIONS" {
			c.AbortWithStatus(204)
			return
		}

		c.Next()
	}
}
