# govc Configuration Example
# Copy this file to config.yaml and customize for your environment

server:
  # Server host and port configuration
  host: "0.0.0.0"
  port: 8080
  
  # HTTP timeouts
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"
  request_timeout: "25s"     # Request processing timeout (should be less than write_timeout)
  
  # Maximum number of repositories
  max_repos: 1000
  
  # Maximum request body size (in bytes)
  max_request_size: 10485760  # 10MB
  
  # Trusted proxy addresses (for X-Forwarded-For headers)
  trusted_proxy: []

auth:
  # Enable/disable authentication
  enabled: true
  
  jwt:
    # JWT secret key - MUST be changed in production!
    # Use environment variable: ${GOVC_JWT_SECRET}
    secret: "${GOVC_JWT_SECRET:-change-this-in-production-use-at-least-32-chars}"
    
    # JWT issuer
    issuer: "govc-server"
    
    # Token time-to-live
    ttl: "24h"

pool:
  # Repository connection pool settings
  max_repositories: 100
  max_idle_time: "30m"
  cleanup_interval: "5m"
  enable_metrics: true

logging:
  # Log level: DEBUG, INFO, WARN, ERROR, FATAL
  level: "INFO"
  
  # Log format: json, text
  format: "json"
  
  # Component name for logs
  component: "govc"
  
  # Output destination: stdout, stderr, or file path
  output: "stdout"

metrics:
  # Enable Prometheus metrics
  enabled: true
  
  # Metrics endpoint path
  path: "/metrics"

storage:
  # Storage type: memory, disk, hybrid
  type: "memory"
  
  # Disk storage path (required for disk/hybrid)
  disk_path: "/var/lib/govc"
  
  # Maximum memory usage in MB
  max_memory_mb: 1024
  
  # Enable caching
  cache_enabled: true
  cache_ttl: "1h"

development:
  # Development mode settings
  debug: false
  profiler_enabled: false
  cors_enabled: false
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"

# Example production configuration with environment variables:
#
# server:
#   host: "${GOVC_HOST:-0.0.0.0}"
#   port: ${GOVC_PORT:-8080}
#
# auth:
#   jwt:
#     secret: "${GOVC_JWT_SECRET}"
#
# logging:
#   level: "${GOVC_LOG_LEVEL:-INFO}"
#
# storage:
#   type: "${GOVC_STORAGE_TYPE:-memory}"
#   disk_path: "${GOVC_STORAGE_PATH:-/var/lib/govc}"