version: '3.8'

services:
  govc-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MAX_REPOS=1000
      - ENABLE_AUTH=false
      - GIN_MODE=release
    volumes:
      # Optional: Mount a directory for persistent repositories
      # - ./data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Optional: Add nginx for TLS termination
  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - govc-server
    restart: unless-stopped

  # Optional: Add Redis for distributed caching
  redis:
    image: redis:alpine
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    restart: unless-stopped